---
language: go
go:
- 1.2.2
- tip
env:
  global:
  - secure: KSHZNPUPweNF6xoDk0uWlfU5wiJHUOvCXtsBUoIHlsC0SRdozgIMjWrDbDEkMKOj84bwOX1SgO2qdabuuz8WTRbS38QpjEd31mbs6wJO0GCsIM3hYalaEWYuH5eVF8VrJbq+AxpyNrnWRbzBGLHZYLGpGvIMfPeD1jYOVzjDNkw=
  - secure: oHjRfKrzOuLDxWv/wffOMrH6WnSjHD4ph5siSGK4Fekdj3bv2/gSji6bxfc03zN+I2DW/dlEJvKKLFMIt5UxAkgS0c9+2WArPOyR1OaLAAJxEqWVL8yUWa62MJORP2E6w55ehP1u2Eponncq6tDdA0+aTsLmq0+YG2RGtToAQWk=
  - PATH=$HOME/gopath/bin:$PATH
  - ARTIFACTS_CONCURRENCY=5
  - ARTIFACTS_S3_BUCKET=meatballhat
  - ARTIFACTS_TARGET_PATHS="artifacts/$TRAVIS_OS_NAME/$(go env GOARCH)/$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER;artifacts/$TRAVIS_OS_NAME/$(go env GOARCH)/$TRAVIS_REPO_SLUG/$TRAVIS_COMMIT"
before_install:
- go get github.com/tools/godep
- go get code.google.com/p/go.tools/cmd/cover
- godep restore
after_success:
- cp -v ${GOPATH%%:*}/bin/artifacts ./artifacts
- export ARTIFACTS_PATHS="$(git ls-files -o | tr "\n" ";")"
- sha256sum $ARTIFACTS_PATHS > SHA256SUMS
- ${GOPATH%%:*}/bin/artifacts upload


# ---------------------------------------------------------------------------
# XXX: This bit is pretend!  Consider it a goal.
# Other than the s3_bucket arg, all of these values would be the defaults.
# ---------------------------------------------------------------------------
artifacts:
  s3_bucket: meatballhat
  private: true
  target_paths:
  - artifacts/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
  concurrency: 3
  retries: 2
  checksums:
  - sha256
  signatures:
  - rsa
  paths:
  - $GIT_UNTRACKED
