---
language: go
env:
  global:
  - PATH=$HOME/gopath/bin:$HOME/bin:$PATH
  - ARTIFACTS_CONCURRENCY=5
  - ARTIFACTS_S3_BUCKET=meatballhat
  - ARTIFACTS_TARGET_PATHS="artifacts/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER:artifacts/$TRAVIS_COMMIT"
  - ARTIFACTS_PERMISSIONS=public-read
  - ARTIFACTS_CACHE_CONTROL='public, max-age=315360000'
  - ARTIFACTS_LOG_FORMAT=multiline
  - ARTIFACTS_DEBUG=1
  - secure: s2EqeZxaJE90bakWEgbscC9uloXWB98vqcS6kEUOxkHByasts4BFm9uQbYu5UhVEUieAIWObt3817MpqxWdRPwRkmbHBuil7bCX3+x4n4JRIqVytl3Paw63xtLM46/VdNwyaJX8qe8//0F6B5KGW0BjWnCzIXYcRu6fCLtCYnno=
  - secure: PRHJRw6Avk/5Q4s/LU6hAb1dOL5PTFG6MZDtzmo5mr1IAZW5CybNILbbDqb2BgIymOJ+rK6Sbp76Dd02jGPjl9JnTaKD/u/FnE1UCWEp1M7mIsw8ofg3yDIJthtrNbGvgtgk9g4KuCBTqWOw64+m8cnlqG9SSAVI/dQ/hzFoKHk=
before_install:
- go get github.com/tools/godep
- go get code.google.com/p/go.tools/cmd/cover
- godep restore
- go install -a -race std
script:
- make all crossbuild
- "[[ $TRAVIS_PULL_REQUEST == false ]] && ./deploy"
- "./install || true"
