---
language: go
go:
- 1.2.2
- tip
env:
  global:
  - PATH=$HOME/gopath/bin:$PATH
  - ARTIFACTS_PATHS=artifacts
before_install:
- go get github.com/tools/godep
- godep restore
after_success:
- ${GOPATH%%:*}/bin/artifacts upload
