---
language: go
go:
- 1.2.2
- tip
env:
  global:
  - PATH=$HOME/gopath/bin:$HOME/bin:$PATH
  - ARTIFACTS_CONCURRENCY=5
  - ARTIFACTS_S3_BUCKET=meatballhat
  - ARTIFACTS_TARGET_PATHS="artifacts/$(go env GOOS)/$(go env GOARCH)/$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER:artifacts/$(go env GOOS)/$(go env GOARCH)/$TRAVIS_REPO_SLUG/$TRAVIS_COMMIT"
  - ARTIFACTS_PERMISSIONS=public-read
  - ARTIFACTS_CACHE_CONTROL='public, max-age=315360000'
  - ARTIFACTS_LOG_FORMAT=multiline
  - ARTIFACTS_DEBUG=1
  - secure: tVVK3d1bO7C01AYrrk/BVQtT8nG/hFHoebnX3dJblvF3CPIZbbq1WmjUbDgDGfJ20qrm1SyRwETMFh7KFk/6mdWVdDvjXeBPKpe+S+C64UN+ztx3CAFhKbGDlaaJWER3N6TULDtCJccrN1EJ4mAM7DFjnB/tnRoaMlDq1Y2zEuM=
  - secure: wTw7YMz6pvXEMAkk94rU7GcJBNXheQRp324oE3dwTXA7l4A3qNiSO4foLoRo4TVmj+nlcMgZb4iENEzvyPxMXn8LfTeiKHZsawaplD4t8fnvon+r/3tqL2t6AjRxFcynoWQ0jZGWyNJgEZeQ7f7nbZ1/W5PQ3XB0bC9m+01EELw=
before_install:
- go get github.com/tools/godep
- go get code.google.com/p/go.tools/cmd/cover
- godep restore
- go install -a -race std
script:
- make
- ./deploy
- ./install
